---
- name: Install Netdata and configure NGINX as a proxy
  hosts: backend
  become: yes

  tasks:
    - name: Install Netdata
      become: yes
      get_url:
        url: "https://my-netdata.io/kickstart.sh"
        dest: "/tmp/netdata-install.sh"
        mode: 0755

    - name: Execute Netdata installation script
      become: yes
      command: "/tmp/netdata-install.sh"

    - name: Start Netdata service
      become: yes
      service:
        name: netdata
        state: started
        enabled: yes
  handlers:
    - name: restart netdata
      become: yes
      service:
        name: netdata
        state: restarted
