- name: Copy SSH public key for passwordless login
  hosts: all
  become: yes
  vars:
    ssh_pub_key_path: "/root/.ssh/id_rsa.pub"
  tasks:
    - name: Ensure the .ssh directory exists
      file:
        path: "/root/.ssh"
        state: directory
        mode: "0700"
    - name: Copy SSH public key to authorized_keys
      ansible.builtin.authorized_key:
        user: root
        key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
        state: present
        path: "/root/.ssh/authorized_keys"
